services:
  docs:
    image: rememberme_back_local_docs
    container_name: rememberme_back_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rememberme_back:/app/rememberme_back:z
    ports:
      - '9100:9000'
    command: /start-docs
